on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install
      run: npm install

    - name: Codegen
      run: npm run codegen

    - name: Build
      run: npm run build

    - name: Webstats Netlify reporter
      id: webstats-netlify-reporter
      uses: voorhoede/webstats-netlify-reporter
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_ID: ${{ secrets.NETLIFY_ID }}
        WEBSTATS_API_KEY: ${{ secrets.WEBSTATS_API_KEY }}
        WEBSTATS_PROJECT_ID: ${{ secrets.WEBSTATS_PROJECT_ID }}