on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Webstats Netlify reporter
      id: webstats-netlify-reporter
      uses: voorhoede/webstats-netlify-reporter@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_ID: ${{ secrets.NETLIFY_ID }}
        WEBSTATS_API_KEY: ${{ secrets.WEBSTATS_API_KEY }}
        WEBSTATS_PROJECT_ID: ${{ secrets.WEBSTATS_PROJECT_ID }}
    
      run: npm ci
      run: npm run codegen
      run: npm run build
      run: npm run save